; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secrets.ini

[common]
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    ${secrets.build_flags}

[env:esp32dev]
platform = espressif32
board = esp32dev
extends = common
build_src_filter = +<*> -<display.cpp> -<display_t190.cpp>

[env:heltec_wireless_paper]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_8mb.csv
; exclude the TFT display implementation for this board
build_src_filter = +<*> -<display_t190.cpp>
build_flags =
    ${common.build_flags}
    -DWIRELESS_PAPER
    -DBUTTON_GPIO=0
lib_deps =
    https://github.com/todd-herbert/heltec-eink-modules

[env:vision_master_t190]
; Note: if the board ID "heltec_vision_master_t190" is not found, update your
; espressif32 platform: `pio pkg update -g -p espressif32`
; or install the Heltec platform package manually.
platform = espressif32
board = heltec_vision_master_t190
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_8mb.csv
; exclude the e-ink display implementation for this board
build_src_filter = +<*> -<display.cpp>
build_flags =
    ${common.build_flags}
    -DVISION_MASTER_T190
    -DBUTTON_GPIO=21
lib_deps =
    https://github.com/HelTecAutomation/Heltec_ESP32
    adafruit/Adafruit GFX Library @ ^1.11.0
    adafruit/Adafruit BusIO @ ^1.14.0
