; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DAP_PASSWORD='"your_password_here"'

[env:esp32dev]
platform = espressif32
board = esp32dev
extends = common

[env:heltec_wireless_paper]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_8mb.csv
build_flags =
    ${common.build_flags}
    -DWIRELESS_PAPER
lib_deps =
    https://github.com/todd-herbert/heltec-eink-modules
